const constants = {
    LENGTH_EDIT_IN: "LENGTH_EDIT_IN",
    LENGTH_EDIT_LI: "LENGTH_EDIT_LI",
    LENGTH_EDIT_MINUS: "LENGTH_EDIT_MINUS",
    LENGTH_EDIT_PLUS: "LENGTH_EDIT_PLUS",
    WiDTH_EDIT: "WiDTH_EDIT",
    STEP_EDIT: "STEP_EDIT",
    KEY_DOWN_EDIT: "KEY_DOWN_EDIT",
    SOPTOVAR_EDIT: "SOPTOVAR_EDIT",

}


export default constants;